exp_name: ~
model_type: BaselineModel
log_dir: ./tb_logger
save_dir: ../exps_horse_test
device: cuda
multi_gpu: false

datasets:
  train_dataset:
    type: SimpleFolderDataloader
    dataroot_img: datasets/weizmann_horse_split/train_split/images
    dataroot_lbl: datasets/weizmann_horse_split/train_split/masks
    img_exts: ['jpg']
    lbl_exts: ['png']
    augment:
      augment_type: simple_aug
      size: 512
    batch_size: 8
    num_workers: 4

  val_dataset:
    type: SimpleFolderDataloader
    dataroot_img: datasets/weizmann_horse_split/valid_split/images
    dataroot_lbl: datasets/weizmann_horse_split/valid_split/masks
    img_exts: ['jpg']
    lbl_exts: ['png']
    augment:
      augment_type: simple_aug
      size: 512

train:
  num_epoch: 100
  model_arch:
    type: SMPArch
    load_path: ~
    backbone: DeepLabV3Plus
    in_channels: 3
    encoder_name: resnet50
    classes: 2

  optimizer:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [80]
    gamma: 0.1

  criterion:
    type: celoss

  metric:
    type: miou

eval:
  eval_interval: 1
